module.exports = [
'Your smile is contagious.',
'You look great today.',
'You are a smart cookie.',
'I bet you make babies smile.',
'You have impeccable manners.'
'I like your style.',
'You have the best laugh.',
'I appreciate you.',
'You are the most perfect you there is.',
'You are enough.',
'You are strong.',
'Your perspective is refreshing.',
'You are an awesome friend.',
'You light up the room.',
'You deserve a hug right now.',
'You should be proud of yourself.',
'You are more helpful than you realize.',
'You have a great sense of humor.',
'You have got all the right moves!',
'Is that your picture next to "charming" in the dictionary?',
'Your kindness is a balm to all who encounter it.',
'You are all that and a super-sized bag of chips.'
'On a scale from 1 to 10, you are an 11.'
'You are brave.',
'Your eyes are breathtaking.',
'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.',
'You are making a difference.',
'You are like sunshine on a rainy day.',
'You bring out the best in other people.',
'Your ability to recall random factoids at just the right time is impressive.',
'You are a great listener.',
'How is it that you always look great, even in sweatpants?',
'Everything would be better if more people were like you!',
'I bet you sweat glitter.',
'You were cool way before hipsters were cool.',
'That color is perfect on you.',
'Hanging out with you is always a blast.',
'You smell really good.',
'Being around you makes everything better!',
'Colors seem brighter when you are around.',
'You are more fun than a ball pit filled with candy.',
'You are wonderful.'
'You have cute elbows. For reals!'
]
